baseURL = "http://biotop.co/xmascal/"
languageCode = "en-us"
title = "Biotop Advent Calendar"
theme = "advent-flex"
publishdir = "docs"

[languages]
  [languages.en]
    title = "Biotop Christmas Calendar"
    contentDir = "content/english"
    languageName = "English"
    weight = 10

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about this project"
        name = "about this project"
        pre = "<i class='fa fa-heart'></i>"
        url = "about/"
        weight = -110

      [[languages.en.menu.main]]
        name = "biotop website"
        post = "<span class='alert'>New!</span>"
        pre = "<i class='fa fa-road'></i>"
        url = "http://biotope.science/"
        weight = -100

      [[languages.en.menu.main]]
        name = "de"
        post = "<span class='alert'>New!</span>"
        pre = "<i class='fa fa-road'></i>"
        url = "/de"
        weight = -90

  [languages.de]
    title = "Biotop Adventkalender"
    contentDir = "content/german"
    languageName = "Deutsch"
    weight = 20

    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "about"
        name = "Über dieses Projekt"
        pre = "<i class='fa fa-heart'></i>"
        url = "about/"
        weight = -110

        [[languages.de.menu.main]]
          name = "biotop website"
          post = "<span class='alert'>New!</span>"
          pre = "<i class='fa fa-road'></i>"
          url = "http://biotope.science/"
          weight = -100

      [[languages.de.menu.main]]
        name = "en"
        post = "<span class='alert'>New!</span>"
        pre = "<i class='fa fa-road'></i>"
        url = "http://biotop.co/xmascal/"
        weight = -70
